version: "3"

services:
  service:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: service
    environment:
      - CONFIG_PATH=./config/local.yaml # prod/dev.yaml
      - LOG_NAMESPACE=service
      - LOG_NAMESPACE=production # development
    ports:
      - "8080:${HTTP_PORT}"